services:
  db:
    image: postgres:16
    container_name: postgres-file-management
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file-management
    ports:
      - "5432:5432"