spring.application.name=file-management
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://app-file-management-database-postgres-service:5432/file-management
spring.datasource.username=${APP_USER_DATABASE}
spring.datasource.password=${APP_PASSWORD_DATABASE}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT
app.jwt.secret=699fcaa2-4d89-4dff-aba8-49776421a0f2
app.jwt.expiration-seconds=3600

# RabbitMQ
spring.rabbitmq.addresses=amqps://rgovhbyf:PleWWS7G5pTsj7faqls2gI_B0HF72o36@seal.lmq.cloudamqp.com/rgovhbyf
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# Queues
rabbitmq.queue.upload=fila.upload

# AWS
aws.s3.bucket-name=file-process-bucket-uuy3c0