# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/file-management
spring.datasource.username=admin
spring.datasource.password=admin123
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
